# Generated by Django 3.0.5 on 2020-04-19 11:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20200419_1653'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='thumbnail1',
        ),
        migrations.RemoveField(
            model_name='blog',
            name='thumbnail2',
        ),
    ]
