# Generated by Django 3.0.5 on 2020-04-23 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20200419_1936'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='city',
            field=models.CharField(default='ahemedabad', max_length=100),
        ),
        migrations.AddField(
            model_name='profile',
            name='skill',
            field=models.CharField(default='developer', max_length=300),
        ),
    ]
